const KEY="strength-log-v2";
const quickAdds=[5,10,15,20,25,50];
const exercises=["Planks","Glute bridges","Deadlifts","Lunges","Push-ups","Resistance bands","Dumbbells","Core work","Other"];
const defaults={goals:{daily:50,weekly:350,monthly:1500},days:{}};
let data=load();let editDate=null;
function todayKey(){return new Date().toISOString().slice(0,10)}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaults)}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function day(k=todayKey()){if(!data.days[k])data.days[k]={squats:[],other:false,exercises:[],notes:""};return data.days[k]}
function total(k){return (data.days[k]?.squats||[]).reduce((a,b)=>a+Number(b),0)}
function fmt(k){return new Date(k+"T12:00:00").toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"})}
function recent(n){const out=[],now=new Date();for(let i=n-1;i>=0;i--){const d=new Date(now);d.setDate(now.getDate()-i);out.push(d.toISOString().slice(0,10))}return out}
function sum(keys){return keys.reduce((s,k)=>s+total(k),0)}
function logged(k){const d=data.days[k];return !!d&&(total(k)>0||d.other||d.exercises?.length||d.notes)}
function streak(){let s=0,d=new Date();while(true){const k=d.toISOString().slice(0,10);if(logged(k)){s++;d.setDate(d.getDate()-1)}else break}return s}
function best(){const vals=Object.keys(data.days).map(total);return vals.length?Math.max(...vals):0}
function render(){renderHome();renderOther();renderProgress();renderHistory();renderGoals()}
function renderHome(){const k=todayKey(),t=total(k),goal=data.goals.daily;document.getElementById("todayDate").textContent=fmt(k);document.getElementById("todayTotal").textContent=t;document.getElementById("dailyGoalText").textContent=`Goal: ${t} / ${goal}`;document.getElementById("dailyProgress").style.width=`${Math.min(100,t/goal*100)}%`}
function renderOther(){const d=day();document.getElementById("exercisePanel").classList.toggle("hidden",!d.other);document.getElementById("otherYes").classList.toggle("active",d.other);document.getElementById("otherNo").classList.toggle("active",!d.other);document.getElementById("exerciseNotes").value=d.notes||"";const chips=document.getElementById("exerciseChips");chips.innerHTML="";exercises.forEach(x=>{const b=document.createElement("button");b.type="button";b.className="chip"+(d.exercises.includes(x)?" selected":"");b.textContent=x;b.onclick=()=>{d.other=true;d.exercises=d.exercises.includes(x)?d.exercises.filter(e=>e!==x):[...d.exercises,x];save();render()};chips.appendChild(b)});document.getElementById("exerciseSummary").textContent=d.other?`Logged: ${d.exercises.join(", ")||"other strength"}`:"No other strength logged today."}
function renderProgress(){const w=recent(7),m=recent(30);document.getElementById("streak").textContent=streak();document.getElementById("weekTotal").textContent=sum(w);document.getElementById("monthTotal").textContent=sum(m);document.getElementById("bestDay").textContent=best();document.getElementById("consistencyText").textContent=`${w.filter(logged).length} workout days in the last 7 days`;const ch=document.getElementById("chart"),dates=recent(14),max=Math.max(1,data.goals.daily,...dates.map(total));ch.innerHTML="";dates.forEach(k=>{const wrap=document.createElement("div");wrap.className="bar-wrap";const bar=document.createElement("div");bar.className="chart-bar";bar.style.height=`${Math.max(4,total(k)/max*100)}%`;bar.title=`${fmt(k)}: ${total(k)}`;const lab=document.createElement("span");lab.className="bar-label";lab.textContent=new Date(k+"T12:00:00").getDate();wrap.append(bar,lab);ch.appendChild(wrap)})}
function renderHistory(){const list=document.getElementById("historyList");const dates=Object.keys(data.days).filter(logged).sort().reverse();list.innerHTML="";if(!dates.length){list.innerHTML='<p class="muted">No history yet. Logged days will appear here.</p>';return}dates.forEach(k=>{const d=data.days[k];const item=document.createElement("div");item.className="history-item";item.innerHTML=`<div class="history-date">${fmt(k)}</div><div class="history-details">${total(k)} squats</div><div class="history-details">Other strength: ${d.other?(d.exercises.join(", ")||"Yes"):"No"}</div>${d.notes?`<div class="history-details">Notes: ${d.notes}</div>`:""}`;const b=document.createElement("button");b.className="secondary";b.type="button";b.textContent="Edit day";b.onclick=()=>openEdit(k);item.appendChild(b);list.appendChild(item)})}
function renderGoals(){document.getElementById("dailyGoal").value=data.goals.daily;document.getElementById("weeklyGoal").value=data.goals.weekly;document.getElementById("monthlyGoal").value=data.goals.monthly}
function addSquats(n){day().squats.push(Number(n));save();render()}
function setup(){const grid=document.getElementById("quickGrid");quickAdds.forEach(n=>{const b=document.createElement("button");b.textContent=`+${n}`;b.onclick=()=>addSquats(n);grid.appendChild(b)});const sel=document.getElementById("customSelect");for(let i=1;i<=200;i++){const o=document.createElement("option");o.value=i;o.textContent=`${i} squats`;sel.appendChild(o)}document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===b.dataset.screen));document.querySelectorAll(".nav-btn").forEach(x=>x.classList.toggle("active",x===b));window.scrollTo({top:0,behavior:"smooth"})});document.getElementById("customBtn").onclick=()=>document.getElementById("customDialog").showModal();document.getElementById("cancelCustom").onclick=()=>document.getElementById("customDialog").close();document.getElementById("addCustom").onclick=()=>{addSquats(sel.value);document.getElementById("customDialog").close()};document.getElementById("repeatBtn").onclick=()=>{const s=day().squats; if(s.length)addSquats(s[s.length-1])};document.getElementById("undoBtn").onclick=()=>{day().squats.pop();save();render()};document.getElementById("clearTodayBtn").onclick=()=>{if(confirm("Clear today's squats?")){day().squats=[];save();render()}};document.getElementById("otherYes").onclick=()=>{day().other=true;save();render()};document.getElementById("otherNo").onclick=()=>{const d=day();d.other=false;d.exercises=[];d.notes="";save();render()};document.getElementById("exerciseNotes").oninput=e=>{const d=day();d.other=true;d.notes=e.target.value;save();renderOther();renderHistory()};document.getElementById("saveGoals").onclick=()=>{data.goals.daily=+document.getElementById("dailyGoal").value||50;data.goals.weekly=+document.getElementById("weeklyGoal").value||350;data.goals.monthly=+document.getElementById("monthlyGoal").value||1500;save();render()};document.getElementById("resetBtn").onclick=()=>{if(confirm("Delete all Strength Log data on this device?")){data=structuredClone(defaults);save();render()}};document.getElementById("exportBtn").onclick=exportCSV;document.getElementById("cancelEdit").onclick=()=>document.getElementById("editDialog").close();document.getElementById("saveEdit").onclick=saveEdit}
function openEdit(k){editDate=k;const d=day(k);document.getElementById("editTitle").textContent=`Edit ${fmt(k)}`;document.getElementById("editSquats").value=total(k);document.getElementById("editNotes").value=d.notes||"";const box=document.getElementById("editChips");box.innerHTML="";exercises.forEach(x=>{const b=document.createElement("button");b.type="button";b.className="chip"+(d.exercises.includes(x)?" selected":"");b.textContent=x;b.onclick=()=>{d.exercises=d.exercises.includes(x)?d.exercises.filter(e=>e!==x):[...d.exercises,x];b.classList.toggle("selected")};box.appendChild(b)});document.getElementById("editDialog").showModal()}
function saveEdit(){const d=day(editDate);const t=+document.getElementById("editSquats").value||0;d.squats=t?[t]:[];d.notes=document.getElementById("editNotes").value;d.other=d.exercises.length>0||d.notes.trim().length>0;save();document.getElementById("editDialog").close();render()}
function exportCSV(){const rows=[["date","squats","other_strength","exercises","notes"]];Object.keys(data.days).sort().forEach(k=>{const d=data.days[k];if(logged(k))rows.push([k,total(k),d.other?"yes":"no",(d.exercises||[]).join("; "),(d.notes||"").replaceAll('"','""')])});const csv=rows.map(r=>r.map(v=>`"${v}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="strength-log.csv";a.click()}
setup();render();if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js");
